include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

image: docker:git

services:
  - docker:dind 

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  #- apt-get update
  #- apt-get install doxygen -y
  #- apt-get install ttf-freefont graphviz -y

  
stages:
#  - build
  - test
  - release
  - deploy

variables:
#  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

release-image:
  stage: release
  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker run --rm -v "$PWD":/app -w /app maven:3-jdk-8 mvn clean install
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE  
#  tags:
#    - docker
  only:
    - master
    
#pages:
#  stage: deploy
#  script:
#  - cd docs
#  - doxygen Doxyfile
#  - mv html ../public 
#  artifacts:
#    paths:
#    - public
#  only:
#  - master
